# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNMercadoPago' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
	use_frameworks!
	platform :ios, '10.0'
	pod 'MercadoPagoSDK', '~> 4.0'

end
